### PR TITLE
Update project dependencies

### PR DESCRIPTION
**Pull request by larmie56**
**What does this PR do?**
- Update the version of the  project's dependencies.

**Description of task to be completed?**
- Update the version of the project's dependencies 
- Modify the package of DefaultExpenseRepositoryTest.kt
- Remove dependency listed twice

### CODE REVIEW

**Comment by Ezike** [comment]
You can also update the AGP and kotlin plugin versions

**Comment by larmie56** [comment]
> You can also update the AGP and kotlin plugin versions

Okay, I will do that now

**Comment by larmie56** [comment]
> You can also update the AGP and kotlin plugin versions

The recent commit doesn't update the AGP version. Been on it since yesterday. 

The AGP update has compatibility issues with Hilt. I tried using the Snapshot version of Hilt, as mentioned [here](https://github.com/google/dagger/issues/2631#issuecomment-844896660), still threw error. Had to revert back to the current version we're using, as the version was suggested [here](https://github.com/google/dagger/issues/2631#issuecomment-863041758)

**Comment by Ezike** [comment]
well done

**Pull request merged**
